### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by sebholstein**
dasdas

### CODE REVIEW

**Comment by sebholstein** [comment]
test

**Comment by sebholstein** [comment]
test2

**Comment by sebholstein** [comment]
test3

**Comment by sebholstein** [comment]
test4

**Comment by SebastianM** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Comment by SebastianM** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Comment by SebastianM** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Comment by sebholstein** [comment]
@a2gm-bot please merge

**Pull request closed without merging**
